name: Deploy to GitHub Pages

on:
  workflow_call:
    inputs:
      artifact_download:
        description: 'Diretorio artefato para publicar'
        required: true
        type: string

jobs:
  github-page:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # informe o name do artefato do job de Upload
      - name: Download a Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: ${{ inputs.artifact_download }}
          path: ${{ inputs.artifact_download }}

      - name: ls repositorio
        run: ls

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ inputs.artifact_download }}