name: Terraform Apply

on:
  push:
    branches:
      - master

  workflow_call:
    inputs:
      tf-action-working-dir:
        description: 'Diretório do terraform no repositório'
        default: '.'
        required: false
        type: string

jobs:

  terraform-apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    steps:

      - name: Terraform Apply
        if: github.ref_name == 'main' || github.ref_name == 'master'
        run: |
          terraform apply -auto-approve -input=false \
          && terraform output > outputs-apply
        env:
          TF_ACTION_WORKING_DIR: ${{ inputs.tf-action-working-dir }}

      - name: Verificar existe outputs.tf 
        id: check_output_file
        uses: andstor/file-existence-action@v1
        with:
          files: "outputs.tf"

      - name: Upload Output Plan
        uses: actions/upload-artifact@v3
        if: steps.check_output_file.outputs.files_exists == 'true'
        with:
          name: outputs-apply
          path: outputs-apply
          retention-days: 1
