name: Terraform Setup

on:
  push:
    branches-ignore:
      - master
  workflow_call:

jobs:
  terraform-setup:
    name: Setup terraform
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
