name: Terraform Setup

on:
  push:
    branches-ignore:
      - master
  workflow_call:
    inputs:
      tf-action-working-dir:
        description: 'Diretório do terraform no repositório'
        default: '.'
      aws-region:
        description: 'AWS Region'
        default: 'us-east-1'
    secrets:  
      aws-access-key-id:
        description: 'AWS Key ID'
        required: true
      aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: true

jobs:
  terraform-setup:
    name: Setup terraform
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.aws-region }}
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}

      - name: Terraform Init
        run: terraform init
        env:
          TF_ACTION_WORKING_DIR: ${{ inputs.tf-action-working-dir }}