name: Terraform Plan

on:
  push:
    branches-ignore:
      - master
  workflow_call:
    secrets:  
      aws-region:
        description: 'AWS Region'
        required: true
      aws-access-key-id:
        description: 'AWS Key ID'
        required: true
      aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: true
jobs:

  terraform-plan:
    name: Verify terraform changes
    runs-on: ubuntu-latest
    steps:
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.aws-region }}
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
      
      - name: Terraform Validate
        run: terraform validate 

      - name: Terraform Plan
        run: |
          terraform plan \
          && terraform output > outputs-plan
        env:
          TF_ACTION_WORKING_DIR: '.'

      - name: Upload Output Plan
        uses: actions/upload-artifact@v3
        with:
          name: output-plan
          path: output-plan
          retention-days: 1
