name: Terraform Setup

on:
  push:
    branches-ignore:
      - master
  workflow_call:
    tf-action-working-dir:
      description: 'Diretório do terraform no repositório'
      default: '.'
      required: false
      type: string

jobs:
  terraform-setup:
    name: Setup terraform
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        run: terraform init
        env:
          TF_ACTION_WORKING_DIR: ${{ inputs.tf-action-working-dir }}