name: Testes Integrados de API com Newman
on:
  workflow_call:
    inputs:
      collection:
        description: 'Nome da coleção'
        required: true
        type: string
      environment:
        description: 'Nome da environment'
        required: true
        type: string
      extra_options:
        description: 'Opções extra para execução do teste'
        required: false
        type: string
      artifact_name:
        description: 'Nome do artefato para upload'
        required: true
        type: string
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Instalar node
      uses: actions/setup-node@v2
      with: 
        node-version: '14.x'
    
    - name: Instalar newman
      run: |
       npm install -g newman newman-reporter-htmlextra

    - name: Testes com Newman
      continue-on-error: true
      run: |
       mkdir -p report
       newman run ${{ inputs.collection }}.json -e ${{ inputs.environment }}.json -r htmlextra --reporter-htmlextra-export report/index.html ${{ inputs.extra_options }}

    - name: Upload relatório da execucao dos testes
      uses: actions/upload-artifact@v3
      with: 
       name: ${{ inputs.artifact_name }}
       path: report
       retention-days: 1
     